# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    env:
      TRAVIS_REPO_SLUG: ${{ github.repository }} 
      TRAVIS_BRANCH: ${{ github.head_ref }} 
      TRAVIS_PULL_REQUEST: ${{ github.event.number }} 
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM Init
      run: npm init -y  
    - name: Install Remark
      run: npm install --global remark-cli remark-validate-links
    - name: Clone Script repo
      run: git clone https://github.com/VoronDesign/GithubScripts.git .github_scripts
    - name: Execute CI
      run: /bin/bash ./.github_scripts/travis/ci-build.sh
